version: '3'

services :
  web:
    container_name: web
    build:
      context: .
      dockerfile: .docker/web/Dockerfile
    ports:
        - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html/:cached
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-mysql}
      DB_USERNAME: ${DB_USERNAME:-mysql}
      DB_PASSWORD: ${DB_PASSWORD:-mysql}
    tty: true
    stdin_open: true
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: .
      dockerfile: .docker/database/Dockerfile
    volumes:
      - ./.database/data:/var/lib/mysql:cached
      - ./.database/logs:/var/log:cached
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-mysql}
      MYSQL_USER: ${DB_USERNAME:-mysql}
      MYSQL_PASSWORD: ${DB_PASSWORD:-mysql}
      TZ: Asia/Tokyo
    ports:
      - ${DB_PORT}:3306
